#!/usr/bin/env python3
"""
pad.py — insert N NOPs after every instruction in a RISC-V assembly file.

Why this exists
---------------
At L3a the pipeline has no hazard hardware: no forwarding, no interlock, and
flush is tied off. Correctness is bought by spacing dependent instructions far
enough apart that the hazard cannot occur. Both hazard classes need the same
distance on this core:

  data    : write-first bypass in reg_file makes a WB write visible to an ID
            read in the same cycle, so a dependent instruction needs 2 slots
            of separation.
  control : branch/jump resolve in EX, so 2 instructions are already in flight
            behind them and are not flushed. They must be harmless.

Two NOPs after every instruction satisfies both without any per-instruction
hazard analysis -- which is the entire point of the L3a milestone. The padded
program is NOT conformant RV32I; hardware is supposed to resolve these. This
is a scaffold that gets deleted at L3b.

Why generate instead of hand-writing
------------------------------------
A hand-written coverage_nop.S is a second copy of the coverage list that will
drift from the original, and the original is what defines "L1 complete". Here
the padding count is an argument, so re-deriving it after a design change is
one command instead of an edit pass over 300 lines.

Safety assumptions (verified against coverage.S)
-----------------------------------------------
  * No pseudo-instructions. `li`, `la`, `mv`, `j`, `ret`, `call`, `beqz` etc.
    expand to multiple instructions AFTER padding is inserted, so the pair
    would end up adjacent with no NOPs between them -- reintroducing exactly
    the hazard this is meant to avoid. `%hi`/`%lo` are fine: lui and addi are
    real instructions.
  * All branches use labels, so the assembler recomputes offsets for free.
  * Labels stay attached to the instruction that follows them, never to the
    padding.

Usage
-----
    python3 pad.py coverage.S            > coverage_nop.S
    python3 pad.py coverage.S --nops 3   > coverage_nop.S
"""

import argparse
import re
import sys

# Mnemonics that the assembler expands into more than one instruction.
# Padding cannot separate the halves of an expansion, so their presence
# silently breaks the guarantee this script is supposed to provide.
PSEUDO = {
    "li", "la", "mv", "not", "neg", "negw", "seqz", "snez", "sltz", "sgtz",
    "j", "jr", "ret", "call", "tail", "nop",
    "beqz", "bnez", "blez", "bgez", "bltz", "bgtz",
    "bgt", "ble", "bgtu", "bleu",
}

LABEL_ONLY = re.compile(r"^[A-Za-z_.$][\w.$]*:$")
LABEL_LEAD = re.compile(r"^([A-Za-z_.$][\w.$]*:)\s*(.*)$")


def strip_comment(line):
    """Return the code portion of a line, with comments removed."""
    for marker in ("#", "//"):
        idx = line.find(marker)
        if idx != -1:
            line = line[:idx]
    return line.strip()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", help="input .S file")
    ap.add_argument("--nops", type=int, default=2,
                    help="NOPs to insert after each instruction (default: 2)")
    args = ap.parse_args()

    with open(args.source, errors="replace") as fh:
        lines = fh.read().splitlines()

    out = []
    in_text = False
    n_instr = 0
    n_pad = 0

    out.append(f"# GENERATED by pad.py from {args.source} -- do not edit.")
    out.append(f"# {args.nops} NOP(s) inserted after every instruction.")
    out.append("# Regenerate with:  python3 pad.py %s --nops %d > <output>"
               % (args.source, args.nops))
    out.append("")

    for raw in lines:
        code = strip_comment(raw)
        out.append(raw.rstrip())

        if not code:
            continue

        # Track which section we're in; only .text gets padded.
        if code.startswith(".section"):
            in_text = ".text" in code
            continue
        if code.startswith("."):
            continue
        if LABEL_ONLY.match(code):
            continue

        # A label may share a line with its instruction.
        m = LABEL_LEAD.match(code)
        if m:
            code = m.group(2).strip()
            if not code:
                continue

        mnemonic = code.split()[0].lower().rstrip(",")
        if mnemonic in PSEUDO:
            sys.stderr.write(
                f"pad.py: ERROR: pseudo-instruction '{mnemonic}' on line: {raw.strip()}\n"
                "  The assembler expands this AFTER padding, leaving the expanded\n"
                "  instructions adjacent with no separation. Rewrite it using real\n"
                "  instructions (e.g. lui/addi with %hi/%lo) before padding.\n")
            sys.exit(1)

        if not in_text:
            continue

        for _ in range(args.nops):
            out.append("    nop")
        n_instr += 1
        n_pad += args.nops

    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(
        f"pad.py: {n_instr} instructions, {n_pad} NOPs inserted, "
        f"{n_instr + n_pad} words total "
        f"({(n_instr + n_pad) * 4} bytes)\n")


if __name__ == "__main__":
    main()
